# Generated by Django 2.2.6 on 2020-02-14 06:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_auto_20191125_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='goods_expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 17, 6, 25, 8, 344931), verbose_name='教材过期时间(默认在创建教材后的三天)'),
        ),
        migrations.AddField(
            model_name='goods',
            name='goods_type',
            field=models.IntegerField(default=0, verbose_name='商品类型0正常1临时'),
        ),
    ]
