# Generated by Django 2.2.6 on 2020-02-18 07:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0004_auto_20200214_0625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='goods_expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 18, 7, 52, 56, 265575), verbose_name='教材过期时间(默认在创建教材后的三个月过期)'),
        ),
    ]
