# Generated by Django 2.2.6 on 2019-11-25 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('curriculum', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='curriculum',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('curriculum_id', models.CharField(max_length=255, unique=True, verbose_name='课程id')),
                ('curriculum_name', models.CharField(max_length=255, verbose_name='课程名称')),
                ('curriculum_good_list', models.CharField(max_length=255, verbose_name='课程内教材列表使用逗号分割')),
                ('db_install_time', models.DateTimeField(auto_now_add=True, verbose_name='入库时间')),
                ('db_update_time', models.DateTimeField(auto_now=True, verbose_name='状态更新时间')),
            ],
            options={
                'db_table': 'GLCCurriculum',
            },
        ),
    ]
