# Generated by Django 2.2.6 on 2020-02-19 02:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0004_auto_20200219_0228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curriculum',
            name='cur_expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 19, 2, 28, 11, 441818), verbose_name='结课时间(默认在创建教材后的三个月过期)'),
        ),
        migrations.AlterField(
            model_name='curriculum',
            name='cur_start_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 19, 2, 28, 11, 441840), verbose_name='开课时间(默认在创建教材时)'),
        ),
    ]
