# Generated by Django 2.2.6 on 2019-11-04 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=255, verbose_name='用户名称')),
                ('pass_word', models.CharField(max_length=255, verbose_name='用户密码')),
                ('user_type', models.IntegerField(default=1, verbose_name='用户类型(0扫描1后台2admin)')),
                ('user_token', models.CharField(max_length=255, verbose_name='临时token有效期一天')),
                ('token_timeout', models.TimeField(verbose_name='token截止的有效期')),
            ],
        ),
    ]
