# Generated by Django 2.2.6 on 2019-11-06 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20191104_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='token_timeout',
            field=models.FloatField(default=0, verbose_name='token截止的有效期'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_token',
            field=models.CharField(default='', max_length=255, verbose_name='临时token有效期一天'),
        ),
    ]
