# Generated by Django 2.2.6 on 2019-11-06 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20191106_1234'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='GLCUser',
        ),
    ]
