# Generated by Django 2.2.6 on 2019-11-23 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('order_id', models.CharField(max_length=255, verbose_name='订单号')),
                ('tracking_id', models.CharField(max_length=255, verbose_name='运单号')),
                ('platform_id', models.CharField(max_length=255, verbose_name='平台订单号')),
                ('other_order_id', models.CharField(max_length=255, verbose_name='换单单号')),
                ('order_status', models.CharField(max_length=255, verbose_name='状态')),
                ('other_param_0', models.CharField(max_length=255, verbose_name='付费方式')),
                ('other_param_1', models.CharField(max_length=255, verbose_name='是否超区')),
                ('other_param_2', models.CharField(max_length=255, verbose_name='超区原因')),
                ('other_param_3', models.CharField(max_length=255, verbose_name='取件码')),
                ('other_param_4', models.CharField(max_length=255, verbose_name='代收货款')),
                ('other_param_5', models.CharField(max_length=255, verbose_name='下单人')),
                ('other_param_6', models.CharField(max_length=255, verbose_name='下单账号')),
                ('other_param_7', models.CharField(max_length=255, verbose_name='下单人部门')),
                ('other_param_8', models.CharField(max_length=255, verbose_name='寄件人')),
                ('other_param_9', models.CharField(max_length=255, verbose_name='寄件人手机')),
                ('other_param_a', models.CharField(max_length=255, verbose_name='寄件人公司')),
                ('user_name', models.CharField(max_length=255, verbose_name='收件人')),
                ('user_phone', models.CharField(max_length=255, verbose_name='收件人手机')),
                ('user_addr', models.CharField(max_length=255, verbose_name='收件人地址')),
                ('user_company', models.CharField(max_length=255, verbose_name='收件人公司')),
                ('order_package_number', models.CharField(max_length=255, verbose_name='包裹数量')),
                ('curriculum', models.CharField(max_length=255, verbose_name='备注')),
                ('order_time', models.DateField(verbose_name='下单时间')),
                ('other_param_b', models.CharField(max_length=255, verbose_name='业务类型')),
                ('other_param_c', models.CharField(max_length=255, verbose_name='物品名')),
                ('other_param_d', models.CharField(max_length=255, verbose_name='生鲜温层')),
                ('other_param_e', models.CharField(max_length=255, verbose_name='返单类型')),
                ('other_param_f', models.CharField(max_length=255, verbose_name='是否保价')),
                ('other_param_10', models.CharField(max_length=255, verbose_name='保价金额')),
                ('expected_time', models.CharField(max_length=255, verbose_name='预计送达')),
                ('order_weight', models.CharField(max_length=255, verbose_name='下单重量(kg)')),
                ('other_param_11', models.CharField(max_length=255, verbose_name='是否拒收')),
                ('other_param_12', models.CharField(max_length=255, verbose_name='验货方式')),
                ('order_state_time', models.CharField(max_length=255, verbose_name='状态更新时间')),
                ('order_db_status', models.IntegerField(default=0, verbose_name='当前订单状态(0待发货1拣货中2待打包3待发货4发货中5已收件6已存档)')),
                ('order_db_install_time', models.DateTimeField(auto_now_add=True, verbose_name='入库时间')),
                ('order_db_update_time', models.DateTimeField(auto_now=True, verbose_name='状态更新时间')),
            ],
            options={
                'db_table': 'GOrder',
            },
        ),
    ]
