# Generated by Django 2.2.6 on 2019-11-23 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20191123_1654'),
    ]

    operations = [
    ]
