# Generated by Django 2.2.6 on 2019-12-12 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_auto_20191123_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_time',
            field=models.CharField(max_length=255, verbose_name='下单时间'),
        ),
    ]
