# Generated by Django 2.2.6 on 2020-01-23 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_auto_20191214_1449'),
    ]

    operations = [
    ]
