# Generated by Django 2.2.6 on 2020-01-23 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_auto_20200123_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_db_status',
            field=models.IntegerField(default=0, verbose_name='当前订单状态(0待拣货1拣货中2待打包3待发货4发货中5已收件6已存档)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(max_length=255, unique=True, verbose_name='订单号'),
        ),
    ]
